CREATE TABLE IF NOT EXISTS {{ params.schema }}.{{ params.table }} (
  course_id      VARCHAR(128) DEFAULT  '1',
  sis_course_id  VARCHAR(128),
  course_code    VARCHAR(128),
  course_name    VARCHAR(128),
  section_name   VARCHAR(128),
  section_id     VARCHAR(128),
  sis_section_id VARCHAR(128),
  teacher_id     VARCHAR(128),
  sis_teacher_id VARCHAR(128),
  teacher_name   VARCHAR(128),
  student_id     VARCHAR(128),
  sis_student_id VARCHAR(128),
  student_name   VARCHAR(128),
  class_date     VARCHAR(128),
  attendance     VARCHAR(128),
  "timestamp"    VARCHAR(128),
  blank          VARCHAR(128),
  run_date       TIMESTAMP DEFAULT GETDATE(),
  PRIMARY KEY(course_id, student_id, class_date))
