version: '3.7'
services:
    postgres:
        image: postgres:13-alpine
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - "${PWD}/db-data:/var/lib/postgresql/data":z

    resetdb:
        image: amazon/mwaa-local:2_8
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - "${PWD}/dags:/usr/local/airflow/dags":z
            - "${PWD}/plugins:/usr/local/airflow/plugins":z
            - "${PWD}/requirements:/usr/local/airflow/requirements":z
        ports:
            - "8080:8080"
        command: resetdb
