SELECT 
  kits.user_id,                                                        
  kits.kit_id,                                                       
  kits.shopify_line_item_id,                                           
  kits.bundle_id,                                                      
  kits.kit_lot,
  kits.registered_at ,
  kits.created_at ,
  kits.kit_service_updated_at ,
  kits.first_delivered_at ,
  kits.recollect_at ,
  kits.first_accessioned_at ,
  kits.last_accessioned_at ,
  kits.cancelled_at ,
  kits.cancel_source,
  kits.is_replacement ,
  kits.id,
  kits.fulfillment_order_id ,
  kits.asset_type ,
  kits.vendor_name ,
  kits.shipment_code ,
  kits.vendor_fulfillment_id ,
  kits.vendor_customer_id ,
  kits.shipment_service_level ,
  kits.outbound_tracking ,
  kits.inbound_tracking ,
  kits.hold_fulfillment_until,
  kits.submitted_at,
  kits.shipped_at,
  kits.shipment_carrier,
  kits.bundlerank,
  kits.expiration_date,
  kits.sku,
  kits.shopify_product_variant_id,
  kits.line_of_business,
  kits.pop_health_partner,
  kits.shipped_to_user_id,
  kits.city ,
  kits.state,
  kits.zip ,
  kits.bundled_vendor ,
  kits.bundled_product ,
  kits.partner_channel ,
  kits.partner_order_number ,
  kits.product_variant_title,
  kits.accession_hold_at ,
  kits.submission_at ,
  kits.extraction_complete_at,
  kits.enrichment_complete_at,
  kits.sequencing_complete_at ,
  kits.needs_interpretation ,
  kits.partner_barcode ,
  kits.prereg_source_id ,
  kits.prereg_registered_at,
  kits.kit_status,
  kits.registered_or_shipped_user,
  kits.kit_bundle_vendor,
  kits.kit_bundle_product,
  kits.kit_needs_interpretation, 
  kits.most_recent_kit_action,
  kits.last_action_at,
  kits.user_kit_rank_desc,

  genomic_order.patient_id,
  genomic_order.order_id,
  genomic_order.procedure_code,
  genomic_order.collection_date,
  genomic_order.received_date,
  genomic_order.external_id_value                                             AS order_external_id_value,
  genomic_order.source_id                                                     AS order_source_id,
  genomic_order.specimen_id                                                   AS order_specimen_id,
  genomic_order.external_id_type                                              AS order_external_id_type,   
  
  genomic_patient.source_id                                                   AS gpatient_source_id,
  genomic_patient.external_id_value                                           AS gpatient_external_id_value,
  genomic_patient.external_id_type                                            AS gpatient_external_id_type,   
  genomic_patient.first_name,                                                    
  genomic_patient.last_name,  
  genomic_patient.date_of_birth,                                               
  genomic_patient.biological_sex,
  
  myhealth_workflow.interp_ordered_at,
  myhealth_workflow.interp_received_at,
  myhealth_workflow.interp_returned_at,
  myhealth_workflow.results_published_at,
  myhealth_workflow.confirmation_triggered_at,
  myhealth_workflow.confirmation_tracked_at,
  myhealth_workflow.confirmation_rejected_at,
  myhealth_workflow.confirmation_ordered_at,
  myhealth_workflow.confirmation_received_at,
  myhealth_workflow.clinical_rev_requested_at,
  myhealth_workflow.clinical_rev_approved_at,

  accessioning_scans.status                                                  AS accessioning_scans_status,
  accessioning_scans.failure_reason,
  accessioning_scans.hold_reason,
  accessioning_scans.created_by_user_id,
  accessioning_scans.created_at_scans,
  accessioning_scans.reviewed_by_user_id,
  accessioning_scans.reviewed_at,
  accessioning_scans.site,
  accessioning_scans.box,
  accessioning_scans.well,
  accessioning_scans.manifest_uploaded_modified_at,
  accessioning_scans.manifest_upload_status,
  accessioning_scans.scan_id,
  accessioning_scans.modified_at,
  accessioning_scans.workflow_type,
  accessioning_scans.cancel_reason

FROM sritest.kits AS kits

LEFT JOIN sritest.accessioning_scans_stage AS accessioning_scans
                    ON kits.kit_id  = accessioning_scans.kit_id

FULL OUTER JOIN sritest.genomic_order_stage AS genomic_order
                    ON kits.partner_barcode = genomic_order.specimen_id

FULL OUTER JOIN sritest.genomic_patient_stage AS genomic_patient 
                    ON kits.user_id =genomic_patient.user_id

LEFT JOIN sritest.myhealth_workflow_custom AS myhealth_workflow
                    ON kits.kit_id = myhealth_workflow.kit_id



