CREATE TABLE IF NOT EXISTS {{ params.schema }}.{{ params.table }} (
        id                VARCHAR(512),
        name              VARCHAR(512),
        summary           VARCHAR(512),
        description       VARCHAR(32768),
        url               VARCHAR(512),
        start             TIMESTAMPTZ,
        "end"             TIMESTAMPTZ,
        created           TIMESTAMP,
        changed           TIMESTAMP,
        published         TIMESTAMP,
        status            VARCHAR(512),
        currency          VARCHAR(512),
        online_event      BOOLEAN,
        venue_address_1   VARCHAR(512),
        venue_address_2   VARCHAR(512),
        venue_city        VARCHAR(512),
        venue_region      VARCHAR(512),
        venue_postal_code VARCHAR(512),
        venue_country     VARCHAR(512),
        venue_id          VARCHAR(512),
        venue_capacity    VARCHAR(512),
        venue_name        VARCHAR(512),
        venue_latitude    VARCHAR(512),
        venue_longitude   VARCHAR(512),
        run_date          TIMESTAMP DEFAULT GETDATE(),
        PRIMARY KEY (id))
